### ISSUE TITLE
Instruction tunning stage question

### ISSUE THREAD

**Issue by OliverLeeXZ** [shikiw/Modality-Integration-Rate#2]
Great work! Have you analysed the MIR in FT stage?

**Comment by shikiw** [comment]
Hi,

Thanks for your insightful question! We did give some tries in FT stage. The results tell that the MIR can generally reflect the benchmark performance but not always perfectly accurate. It might because the high benchmark performance depends not only on the strong cross-modal alignment (which MIR measures well) but also on the model comprehension on the particular knowledges relevant with the benchmark questions.

**Comment by OliverLeeXZ** [comment]
I see, thanks for your response!
